version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db_pass
    ports:
      - 5432:5432
    volumes:
      - exchange_rate_data:/var/postgres/exchange_rate_data

volumes:
  exchange_rate_data:
